menus = [
    {
        "name": "Nasi Goreng Telor",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "tidak_pedas",
        "price": 15000,
        "available_time": ["siang", "malam"],
        "sold_count": 210,
    },
    {
        "name": "Nasi Goreng Bakso",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "sedang",
        "price": 17000,
        "available_time": ["siang", "malam"],
        "sold_count": 180,
    },
    {
        "name": "Nasi Goreng Ayam",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "sedang",
        "price": 19000,
        "available_time": ["siang", "malam"],
        "sold_count": 230,
    },
    {
        "name": "Nasi Goreng Ayam Bakso",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "pedas",
        "price": 20000,
        "available_time": ["siang", "malam"],
        "sold_count": 150,
    },
    {
        "name": "Nasi Goreng Spesial",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "pedas",
        "price": 24000,
        "available_time": ["siang", "malam"],
        "sold_count": 120,
    },
    {
        "name": "Nasi Goreng Ikan Asin",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "sedang",
        "price": 22000,
        "available_time": ["siang"],
        "sold_count": 90,
    },
    {
        "name": "Nasi Goreng Kambing",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "sedang",
        "price": 28000,
        "available_time": ["siang"],
        "sold_count": 75,
    },
    {
        "name": "Nasi Goreng Seafood",
        "category": "nasi_goreng",
        "type": "goreng",
        "spice": "pedas",
        "price": 26000,
        "available_time": ["siang", "malam"],
        "sold_count": 140,
    },
    {
        "name": "Mie Goreng Ayam",
        "category": "mie",
        "type": "goreng",
        "spice": "sedang",
        "price": 17000,
        "available_time": ["siang", "malam"],
        "sold_count": 200,
    },
    {
        "name": "Mie Goreng Seafood",
        "category": "mie",
        "type": "goreng",
        "spice": "pedas",
        "price": 20000,
        "available_time": ["siang", "malam"],
        "sold_count": 110,
    },
    {
        "name": "Mie Kuah Ayam",
        "category": "mie",
        "type": "kuah",
        "spice": "sedang",
        "price": 18000,
        "available_time": ["malam"],
        "sold_count": 160,
    },
    {
        "name": "Mie Kuah Bakso",
        "category": "mie",
        "type": "kuah",
        "spice": "tidak_pedas",
        "price": 19000,
        "available_time": ["malam"],
        "sold_count": 220,
    },
    {
        "name": "Mie Kuah Seafood",
        "category": "mie",
        "type": "kuah",
        "spice": "sedang",
        "price": 22000,
        "available_time": ["malam"],
        "sold_count": 95,
    },
    {
        "name": "Bihun Goreng Ayam",
        "category": "bihun",
        "type": "goreng",
        "spice": "sedang",
        "price": 17000,
        "available_time": ["siang", "malam"],
        "sold_count": 130,
    },
    {
        "name": "Bihun Kuah Seafood",
        "category": "bihun",
        "type": "kuah",
        "spice": "sedang",
        "price": 21000,
        "available_time": ["malam"],
        "sold_count": 85,
    },
    {
        "name": "Bihun Goreng Sapi",
        "category": "bihun",
        "type": "goreng",
        "spice": "pedas",
        "price": 20000,
        "available_time": ["siang"],
        "sold_count": 115,
    },
    {
        "name": "Kwetiau Goreng Seafood",
        "category": "kwetiau",
        "type": "goreng",
        "spice": "pedas",
        "price": 23000,
        "available_time": ["siang"],
        "sold_count": 125,
    },
    {
        "name": "Kwetiau Kuah Ayam",
        "category": "kwetiau",
        "type": "kuah",
        "spice": "tidak_pedas",
        "price": 20000,
        "available_time": ["malam"],
        "sold_count": 90,
    },
    {
        "name": "Kwetiau Goreng Sapi",
        "category": "kwetiau",
        "type": "goreng",
        "spice": "sedang",
        "price": 21000,
        "available_time": ["siang"],
        "sold_count": 110,
    },
    {
        "name": "Capcay Goreng Ayam",
        "category": "capcay",
        "type": "goreng",
        "spice": "tidak_pedas",
        "price": 19000,
        "available_time": ["siang"],
        "sold_count": 150,
    },
    {
        "name": "Capcay Kuah Seafood",
        "category": "capcay",
        "type": "kuah",
        "spice": "tidak_pedas",
        "price": 24000,
        "available_time": ["malam"],
        "sold_count": 80,
    },
    {
        "name": "Capcay Goreng Seafood",
        "category": "capcay",
        "type": "goreng",
        "spice": "pedas",
        "price": 25000,
        "available_time": ["siang"],
        "sold_count": 70,
    },
    {
        "name": "Mie Goreng Biasa",
        "category": "mie",
        "type": "goreng",
        "spice": "tidak_pedas",
        "price": 16000,
        "available_time": ["siang", "malam"],
        "sold_count": 250,
    },
    {
        "name": "Bihun Kuah Ayam",
        "category": "bihun",
        "type": "kuah",
        "spice": "sedang",
        "price": 17500,
        "available_time": ["malam"],
        "sold_count": 155,
    },
    {
        "name": "Kwetiau Kuah Seafood",
        "category": "kwetiau",
        "type": "kuah",
        "spice": "sedang",
        "price": 23000,
        "available_time": ["malam"],
        "sold_count": 105,
    },
]